<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

abstract class BaseModel extends Model
{
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
